### ISSUE TITLE
E1 run through

### ISSUE THREAD

**Issue by gnear** [AFADoomer/Wolf3D-TC-3.0#1]
Hey AFADoomer, love the mod and the new menus --- some of the bugs I encounted could be due to git build (gzdoom-x86-g3.8pre-562-g4cf90d70a) I am only able to get it to run on git builds which I guess is because of the new interface stuff 

couple of issues I noticed from E1 playthrough -- managed to bug out a dog by killing it just as it started its bite animation, it played it's death animation and sound but was actually still alive and invincible after that --- the initial kill was counted in the total enemy kill count at the end of the round but the dog was still alive running around after me (and was able to hurt me but not take damage) 

2nd, gattlinggun is missing the 2nd shoot frame? so only has one frame when holding down fire 

3rd, also noticed when picking up the gattlinggun the death-incarnate face/smile isnt shown in the HUD 

all minor things though, love the mod and it's recreation of the original feel :) 

thanks
Scubbo

**Comment by AFADoomer** [comment]
Thanks very much for the feedback!  Sorry about the git build requirement; I haven't even tested this build in 3.7.2 - I have the git builds installed, so that's what I'm using.

Most of these issues are fixed now...  I could never recreate the "undead dog" issue, though.  Are you able to make that happen repeatedly?  I may just add an extra zero-health check into the chasing state and call it good...

**Comment by gnear** [comment]
awesome thanks AFADoomer, 

have noticed when starting new games or warping level after having spawned once already the load screen shows 8 ammo and you start with a pistol but you actually have 0 ammo when spawning with the pistol, so when you go to shoot you end up switching to Knife  (seems to be intermittent, Bring It on via the menu seems to trigger it ? SKILL 2? ?!??! hard to pinpoint why/when it does other than warp level once you've already started a game before that causes it, but also means if you start new game from the menu after warping once you always spawn with 0 ammo 

Haven't been able to replicate dog-invincible mode since - :) 

great to have the gattlinggun spin it's 2 frames again :) 

I minor difference on the E3L0~ (secret level) when a ghost touches  you, you loose health but don't screen-burn RED like you did in the original (or maybe i'm not remembering it right @_@) 


thanks !

**Comment by gnear** [comment]
just another quicky, when loading the new level while having the gattlinggun selected, you spawn with constant smile in the HUD lol, it doesnt change when getting his or swapping weapon etc

**Comment by gnear** [comment]
tested again since fixed, all good, beautiful work AFADoomer, really love it, makes me want to learn zdoom mapping to make some 2.5D-ish levels in the wolf theme
