### ISSUE TITLE
Fatal error: Script error in animdefs.txt line 15

### ISSUE THREAD

**Issue by mrmatteastwood** [AFADoomer/Wolf3D-TC-3.0#10]
Hi, @AFADoomer! Downloaded Wolf3D-TC as a .zip today and threw it in ZDL. When I tried to launch, this error message appeared:

![image](https://user-images.githubusercontent.com/22120259/199785339-7f0859be-6d00-40b0-a6bd-6d23260401c2.png)

I removed line 15 from that file just to see what would happen, and it didn't help.

**Specs:**
OS: Linux Mint 21
GZDoom version 4.8.2
ZDL version 3.1.1
Full system specs: https://termbin.com/zw8n

**Settings in ZDL:**
![image](https://user-images.githubusercontent.com/22120259/199785680-a2d6dedf-654b-4de4-b235-3c2e4796cf63.png)

**Comment by AFADoomer** [comment]
Due to a couple of new features, the current codebase requires one of the more recent [dev builds](https://devbuilds.drdteam.org/gzdoom/) of GZDoom.  

I'm not familiar with how ZDL's IWAD selection works, but you also should be able to set the mod up to be loaded as an IWAD.

**Comment by mrmatteastwood** [comment]
Ah, I understand. Looks like I'll need to wait until a new Linux version drops, the latest dev builds I see are from late August and they don't seem to work. Also, when attempting to add the game as an IWAD, it won't accept zip files. It should be something like .pk3 I think.

**Comment by mrmatteastwood** [comment]
Hey, just to confirm, it works with GZDoom 4.9.0a. How would I go about unlocking the full episodes with all levels from both Wolfenstein and Spear of Destiny?

**Comment by AFADoomer** [comment]
Thanks for the report!  To unlock all of the levels, you need to put the GAMEMAPS.WL6 and/or GAMEMAPS.SOD/.SD2/.SD3 files into the same directory as the .ipk3 file.

**Comment by mrmatteastwood** [comment]
Splendid, thanks!
