### ISSUE TITLE
Ceiling lamp sprite overlapping enemies

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#12]
![20221112155320_1](https://user-images.githubusercontent.com/8591462/201480025-651e197e-3e1b-48cf-b600-3cfd5e8eb4c6.jpg)
It seems the bright circle under the ceiling lamps has a higher pri than sprites.
It could potentially overlap also dead bodies (not tested)?

**Comment by AFADoomer** [comment]
This is how it worked in Wolf3D 😄.

It also can't really be fixed...  The lamp sprites *are* closer to the player, so should draw on top until the guard gets closer than the lamp to the player, and then the draw order will be corect.

**Comment by Hexaae** [comment]
Ah ok, didn't notice in the original game and thought they were 2 different sprites.
