### ISSUE TITLE
Low sound when picking up weapons

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#16]
The sound when picking up weapons has a very low volume (for example first machine gun on E1L1)

**Comment by AFADoomer** [comment]
All of the sounds were ripped at the same time, so there should be no volume difference between them...

Are you hearing the ammo pickup as quiet, too?

**Comment by Hexaae** [comment]
No other sounds are ok, but picking up weapons sounds particularly low

**Comment by AFADoomer** [comment]
Does the pickup sound for the flamethrower or rocket launcher ("summon wolfflamethrower" or "summon wolfrocketlauncher") play at the same volume as an ammo pickup? (They should be the same sound right now).  

I can't reproduce what you are hearing - or I'm not hearing things the same as you, so trying to rule out possibilities.

**Comment by Hexaae** [comment]
"summon wolfmachinegun" seems to have a lower sound compared to those other two.

**Comment by AFADoomer** [comment]
It's the same volume as in WDC (Wolf3D editor) and Wolf3D for me.

**Comment by Hexaae** [comment]
Ok, thank you. Maybe this is just how that specific MIDI sample sounds on my config.
