### ISSUE TITLE
Requests: keyboard layout, ESC... 

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#17]
Some requests:
- support for localized keyboard layouts for special keys (e.g. - and + US keys after the 0) https://www.farah.cl/Keyboardery/A-Visual-Comparison-of-Different-National-Layouts/#it ?
- ESC during game will bring up Options Menu. Pressing ESC again at this point should go back to game instead of acting as exit. Only when player is already in-game at least (original game behavior).
- "End Game" menu option (to go back and select another chapter if you have installed expansions like Spear of Destiny etc.) is available only in Options Menu while playing. This means if you selected the wrong chapter, you must: start a new game first, ESC, End Game...
- No "Read This!" menu item, in-game manual with the story? :)
![ECWolf 1 3 3 (r161001-0413) 02_12_2022 10_29_11](https://user-images.githubusercontent.com/8591462/205261143-e05b4afa-15b9-4143-8f40-86b47f38da14.png)

**Comment by Hexaae** [comment]
Mmmh, I was wrong about ESC key: just re-checked the original with DOSBox... but it still can be a handy feature IMHO ;)

**Comment by AFADoomer** [comment]
ESC key behavior can already be set in the menu.

I'm not sure what you mean about keyboard support...  If GZDoom supports it, this mod does - but if it's an engine limitation, I can't change that.

**Comment by Hexaae** [comment]
> I'm not sure what you mean about keyboard support... If GZDoom supports it, this mod does - but if it's an engine limitation, I can't change that.

I meant the fact - and + on US keyboard are the keys after 0, but may vary on different country layout...

**Comment by AFADoomer** [comment]
The 'Read This' entry only shows up in Shareware and 3-episode Wolf3D, not the full 6-episode version.  The shareware version of the screen is present.  Since I can't find a the hash of of the GAMEMAPS.WL3 file, it's not supported, though most code is in place to do so - but as a result, I never added the other version of the Read This screen.

I still don't know what you mean with keyboard layouts.  What isn't working?

**Comment by AFADoomer** [comment]
Added registered version of 'Read This' entry to menu and set 'End Game' menu entry to always be shown in a0af53a73b4700bcdecae52f8c3c59216e5cf0b5.

**Comment by Hexaae** [comment]
Read This: missing top-left BACK button image. Can you please map RMB as 'previous' (LMB = 'next' already)? 

TESTMAP is missing the _wolfmachinegunlost_.

Can you add ~10% red color layer immediately when you get killed, before the camera starts rotating towards your killer? Original game style.

The keyboard layout thing: the idea was to localize some keys. For example original Wolf3D uses - and + keys positioned after the ..7890 key on the US/UK keyboard, that are in another position (another key code) on German, Italian, etc. keyboards. Not sure is worth it, but could be a low pri "improvement" ;)

Small detail about final death sequence -> hi-scores: original game uses red fade-out to black quickly, and then the scores fade in. Current TC does a red fade-out directly to the scores and sometimes the hi-scores screen appears too early behind the red fade-out.

What about speeding up Get-Psyched! -> game, just a little bit?

**Comment by AFADoomer** [comment]
Read This back button and RMB change added in a78774d8af6efe2cf78d83428504e97b7c682014.

Fade to red on death restored in e07a7ed2ee0af046ddccb91545e3edc19a629da6.  It's not 100% accurate, because the fade remains while the fizzle draws, but I'm pretty sure that was a limitation of the original engine, not necessarily intended appearance.

I can't change anything with the keyboards...  That's a GZDoom limitation.

I'll look at the high score screen again.

I'm not planning on changing the Get Psyched screen...  It is already pretty fast - comparable to DOSBox Wolf3D with significantly increased CPU cycles.  

The red fizzle death is very machine dependent...  I'll see if I can allow customizing the speed, but players may just need to disable it in the menu if it's too slow..

**Comment by AFADoomer** [comment]
Sped up Get Psyched in 400cbf1d37e9c27caee2e8aaeaf85a3f41b45615.

Not sure I can easily change the High Score screen behavior, and confirmed, I can't easily speed up the fizzle death without killing performance even more.

**Comment by Hexaae** [comment]
> Fade to red on death restored in [e07a7ed](https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/e07a7ed2ee0af046ddccb91545e3edc19a629da6).

Can the red fade-in be faster when you got shot? Original Wolf3D used a much faster red fx layer transition (let's say 30-50% faster than current TC).

**Comment by AFADoomer** [comment]
No.  That's a GZDoom limitation.  The damage fade is capped and will only fade to a max amount over a set amount of time.

**Comment by Hexaae** [comment]
So shortening time won't make it more flash-like?

**Comment by AFADoomer** [comment]
Hmmm...  yes...  With the limitation that that the pain flash translucency is tied directly to the amount of damage taken by the player (maxing out at a value of 100), and the engine hard-codes the max screen flash at 175/255 (around 68% translucent).  So I can make it fade back faster, but it won't ever be as "solid" looking as the original.  

What do you think after 77becd54a20074cf8176ae81bf5ddb19db6f8fd2?

**Comment by Hexaae** [comment]
https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/f6c3acdcc89e5da42b8b8c50b008853f30005dca 
looks good to me!

BTW, just noticed another strange thing when you lose all lives: after the hi-scores when you return to Main Menu ESC/RMB will do a strange screen refresh and there is the "Back to Game" option highlighted... ? Expected behavior: since you had game over, should act just like when you quit back to Main Menu or load the game for the first time ( = ESC = want to quit, and no "Back to Game").

**Comment by AFADoomer** [comment]
Addressed all of these in 0d0765aff17f042ee5364439bbc01ccda7639f19.

High scores isn't perfect - no black fade, just fade in from red.

**Comment by Hexaae** [comment]
Great!
It's a decent solution, for now ;)
Thank you for your patience :)
