### ISSUE TITLE
Still about difficulty: chasing guards

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#18]
My impression or original Wolf3D's Nazis once they hear/see you will chase player more than TC?
Sometimes I've seen guards walking away after they detected the player or if you shoot behind a door, won't chase you immediately opening the door and shooting etc. in a more aggressive way like original game... I'm playing at Death Incarnate level.

**Comment by AFADoomer** [comment]
Try after f6c3acdcc89e5da42b8b8c50b008853f30005dca.  I redid a chunk of movement handling - No longer using GZDoom's A_Chase at all, and tweaked a few other things.

**Comment by Hexaae** [comment]
Much closer to original game AI now, with the same expected aggro. Than you!
