### ISSUE TITLE
Operation Eisenfaust missing sprites

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#19]
https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/9c875319a084b1896a7da758337462407183ed5b
Operation Eisenfaust game shows placeholders (error: Unknown type 21005):
![Floor 1 - Wolfenstein 3D TC 06_12_2022 07_07_43](https://user-images.githubusercontent.com/8591462/205835121-61b81715-a966-4153-9486-7bd1a552bea2.png)
![Floor 1 - Wolfenstein 3D TC 06_12_2022 07_07_50](https://user-images.githubusercontent.com/8591462/205835134-275f5496-3e98-4b5e-8ca1-dae2ca511dcc.png)

**Comment by Hexaae** [comment]
P.S.
TESTMAP is missing _wolfknifelost_ _wolfpistollost_ and _wolfmachinegunlost_ weapons and has a strange very dark, almost all black, room...

**Comment by AFADoomer** [comment]
I'll check the placeholder issue later today.

TESTMAP is all intentional...  use the console to manually change the 'g_sod' CVar to 1, 2, or 3 and restart the map to swap between Wolf and SoD and Lost Episodes versions of pickups.

**Comment by Hexaae** [comment]
> TESTMAP is all intentional... use the console to manually change the 'g_sod' CVar to 0, 1, 2, or 3 and restart the map to swap between Wolf and SoD and Lost Episodes versions of pickups.

Oh, so it adapts to the game edition (Classic, Spear of Destiny, Lost Episodes)... I've been cheated by the fact that playing Lost Episodes chapters, and using "map testmap" you can collect original _wolfknife_ and _wolfpistol_ (you start Lost Episodes with _wolfknifelost_ and _wolfpistollost_)

**Comment by AFADoomer** [comment]
The missing actors should be fixed in 79d0718b30209ecaf110481cd2fb96e117fcfd63.  I also fixed being able to manually change g_sod in any map, then restarting the map to reload with that base game's pickups/enemies/etc.

I only made 'classic' versions of the knife and pistol pickups...  They're extras, so I wasn't planning to making Lost variants (just like the rocket launcher, flamethrower, backpack, berserk, breakable column, and exploding barrel).

**Comment by Hexaae** [comment]
Actors fixed, confirmed.

> I only made 'classic' versions of the knife and pistol pickups... They're extras, so I wasn't planning to making Lost variants (just like the rocket launcher, flamethrower, backpack, berserk, breakable column, and exploding barrel).

Mmmh, removing them altogether or adapt them to the g_sod version would be more coherent IMHO.
