### ISSUE TITLE
No SoD/RtD/UC expansion packs

### ISSUE THREAD

**Issue by ghost** [AFADoomer/Wolf3D-TC-3.0#2]
Why are they removed?

**Comment by MateusAuri** [comment]
According to the latest commit notes, SoD is ported but not available through the menu yet, although you can access it through the console.

**Comment by mrmatteastwood** [comment]
Hey @AFADoomer, I really love this TC and I've been meaning to re-play it. I don't quite understand how to get to the SoD etc levels, and if I understand correctly, they're currently buggy?

Do you have an ETA for when their new implementation could be ready? Meanwhile, what would I need to type into the console to play those levels?

Thanks for the amazing work. :-)

**Comment by mrmatteastwood** [comment]
Hey @AFADoomer, is this TC still under development? It would be awesome to be able to access the SoD levels from a menu system again. Really appreciate your work on this.

**Comment by AFADoomer** [comment]
This is resolved in current builds.
