### ISSUE TITLE
[Suggesstion] Add an Option for the MIDI Synth Music

### ISSUE THREAD

**Issue by Trimint123** [AFADoomer/Wolf3D-TC-3.0#21]
Self explanatory; Use the original music files by Bobby Prince, which he shared from his website.

Here's where you can get the MIDI files. (Shoutout to Doomkid for the Archive)
https://www.youtube.com/watch?v=VL5NRTH4KiI

**Comment by AFADoomer** [comment]
Added in b9d5076df5d3e040d1ea74d376ca0adff708f2ba.

Toggleable in the menu of via the 'g_musicstyle' CVar.  It won't sound quite like on youtube unless you configure the soundfont that they used, but I'm not going to go that far.

**Comment by Trimint123** [comment]
Godspeed! Also, I wasn't saying that I need to make it sound like the ones on the YouTube video. I just consider to add MIDI soundtrack.

**Comment by Trimint123** [comment]
Oh, this is something I just noticed; the Result Screen didn't play the MIDI file.

**Comment by AFADoomer** [comment]
Thanks!  Should be fixed in 1a651c0b67cf3dfcde9583ac0603d8dc7ecd9667.

**Comment by Trimint123** [comment]
And now I just discover this when noclipping around. I'm guessing the script thought the dots at the end of the letter was a part of a file call or something.
![image](https://user-images.githubusercontent.com/25479107/208437621-fc3bcf96-98a3-4391-b51d-3aa68aa990b8.png)

Maybe it's a good idea if ya change the MIDI file names, just in case something like this happened. Like `M_[SONGFILE]` or something.
