### ISSUE TITLE
Invisible Controller Menu

### ISSUE THREAD

**Issue by AcerUp** [AFADoomer/Wolf3D-TC-3.0#22]
Recently discussed this in the ZDoom forums, the controller menu is not visible where you adjust the different axis commands. I heard you don't have a controller to use to test this, is there a way I can help you get one? I have plenty to spare or perhaps there's another way...

**Comment by AFADoomer** [comment]
Thanks for the offer.  I was able to rig something up using an app on my phone...  Should be fixed after 699f09c049a0e8c94313826e6aa3d57be484caff.

**Comment by AcerUp** [comment]
Works now, nice!
