### ISSUE TITLE
Ghosts in E3L9 are not present

### ISSUE THREAD

**Issue by AcerUp** [AFADoomer/Wolf3D-TC-3.0#23]
The flamethrower ghosts in E3L9 are replaced with an error exclamation mark.

**Comment by Hexaae** [comment]
Confirmed. Same as old bug https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/19

**Comment by AFADoomer** [comment]
Should be fixed in 8fbfddfe0153fefbed243bdb5762ebb0c5e5983f.

**Comment by AcerUp** [comment]
Works now, thanks.
