### ISSUE TITLE
Game not launching with new updates

### ISSUE THREAD

**Issue by weishen1121** [AFADoomer/Wolf3D-TC-3.0#25]
Hi, I'm getting the following errors:

> Script warning, "Wolf3D-TC-3.0-master.pk3:scripts/menus/genericoptionmenu.zs" line 1063:
> Accessing deprecated function MSTime - deprecated since 4.8.0, Use MSTimeF instead
> Script warning, "Wolf3D-TC-3.0-master.pk3:scripts/menus/extendedoptionmenu.zs" line 1242:
> Accessing deprecated function MSTime - deprecated since 4.8.0, Use MSTimeF instead
> Script error, "Wolf3D-TC-3.0-master.pk3:scripts/eventhandlers/gamehandler.zs" line 166:
> Unknown function GetEpisodeName
> 
> Execution could not continue.
> 
> 1 errors while parsing DECORATE scripts

Last time something like this happened, updating to a recent dev release seemed to fix the issue but when I update now, the menu is blurry, hand gripping gun is huge - takes up the whole page, can't select any level except level 1 and other small weird bugs keep happening.

The last Wolf3D-TC-3.0 version I had working was from 10-26 so it's been about 2 months and I'm sure a lot of great updates so I'd really like to get this working if possible but for now, I have restored my backups and using that with GZdoom version 4.8.9999. 

Could someone please recommend which version of GZdoom to use with the most recent Wolf3D-TC-3.0 update? or maybe upload their version so I can try? I've tried all of the ones from here: https://devbuilds.drdteam.org/gzdoom/ but they have weird bugs going on as mentioned above.

**Comment by AFADoomer** [comment]
Use the latest release version of GZDoom from [the download website](https://zdoom.org/downloads).  It's version 4.10 right now - that's what I'm testing on, anticipating a release in the next week or so.

The MSTime function deprecation that you are getting was reverted on 9 October, so I'm not sure how old your dev build is.

If you are still getting weird bugs, make sure you don't have any other mods loaded or auto-loaded.

**Comment by weishen1121** [comment]
> Use the latest release version of GZDoom from [the download website](https://zdoom.org/downloads). It's version 4.10 right now - that's what I'm testing on, anticipating a release in the next week or so.
> 
> The MSTime function deprecation that you are getting was reverted on 9 October, so I'm not sure how old your dev build is.
> 
> If you are still getting weird bugs, make sure you don't have any other mods loaded or auto-loaded. There was also a change that requires you to put the GAMEMAPS files from your Wolf3D and Spear of Destiny installations into the same folder as the mod in order to be able to play those maps.

Thanks for the quick update!

Putting the gamemaps files in main directory seem to have fixed the issue of levels. I renamed SOD 2 and 3 to .SD2 and .SD3 since they were all .SOD and everything seems perfect now.

Removing the 'Better_Weapons_textures.pk3' mod fixed the big hand gripping bug that would take up the whole screen.
-would there be anyway to get this working again or does it just not work with the new updates?

I fixed the blurriness by changing Hardware Accelerated to Doom Software Renderer which was weird since Hardware Accelerated was what I used before but the scaling size doesn't seem to save after a restart. I went into Choose Resolution Preset, selected 4K, hit the "apply changes (fullscreen)" which was good but when I restarted, it was back to 320x200. I also tried the 'save current settings' but that didn't seem to do anything.

One last thing, would it be possible to skip the 'thanks for playing' screen when exiting the game? 

I thought I had some of these settings fixed with my gzdoom_portable.ini file but I think the new versions of gzdoom might have changed a few things... sorry for all the questions.

**Comment by AFADoomer** [comment]
OK, just added some logic in 90698964ec511b2cc7bd19401b4a123c55135abf so that only 64x64 (or smaller) square textures get the weapon scaling applied; all others are displayed as normal.  This means that the Better Weapon Textures sprites show properly, though their Y offsets are wrong now after I changed the mod's weapon offset handling a while ago.

**Comment by weishen1121** [comment]
> OK, just added some logic in [9069896](https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/90698964ec511b2cc7bd19401b4a123c55135abf) so that only 64x64 (or smaller) square textures get the weapon scaling applied; all others are displayed as normal. This means that the Better Weapon Textures sprites show properly, though their Y offsets are wrong now after I changed the mod's weapon offset handling a while ago.

Dude you are so awesome. Everything works perfectly now. 
Thank you so much for all your hard work!

**Comment by weishen1121** [comment]
Oh man I'm so sorry, I messed things up. 

I just realized there is a newer version of Better Weapon Textures posted in the Issues tab and the one I uploaded earlier in this thread was a really old version. With the new version of Better Weapon Textures, the gun is hidden behind the bottom bar so only the very tip of the gun is shown - here is a picture of what I mean: https://i.imgur.com/f8PUwQu.png
With the old version, I noticed the Y offset was a little off, but it was still pretty good - here is a picture of what it looked like - https://i.imgur.com/boWd48D.png

I think this has something to do with the newly added logic in 9069896 that you posted after I provided you with the old version of Better Weapon Textures. I'm so sorry! 

Here is the link to the newest version from ~3 weeks ago that I just downloaded: https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/7#issuecomment-1339406964

Would there be anyway to manually adjust the Y offset somewhere in an ini file or something?

**Comment by weishen1121** [comment]
Also would it be possible to change the text size without changing the hud scaling when pressing using auomap: https://i.imgur.com/RnjYXXf.png

**Comment by AFADoomer** [comment]
The 'give everything' console command will give you the extra weapons (plus backpack). 

I posted in #7 to ask that they re-update their pack after I changed weapon scaling again.

**Comment by AFADoomer** [comment]
The 'con_scaletext' Cvar ("Scale text in high res" in the Message Options menu) is used to calculate the text scale.

**Comment by weishen1121** [comment]
Ah perfect, thanks so much!
