### ISSUE TITLE
How to play registered/non-shareware episodes?

### ISSUE THREAD

**Issue by stevenvachon** [AFADoomer/Wolf3D-TC-3.0#26]
I have the files for the original DOS games, but I'm not sure what to do with them as they're not *.wad files

**Comment by AFADoomer** [comment]
Just copy the GAMEMAPS files into the folder with the ipk3.

**Comment by stevenvachon** [comment]
Thanks! How about the file name conflicts between the three SoD episodes?

**Comment by stevenvachon** [comment]
Thanks! That works for the SoD files, but not regular Wolfenstein 3D's GAMEMAPS.WL6 file; it gets loaded in the GZDoom log, but the episodes are not selectable

**Comment by AFADoomer** [comment]
That usually means that your file was altered at some point.

Are you running the latest version pulled from here on GitHub?  If so, it should give you an error message partway through the startup log.

**Comment by stevenvachon** [comment]
Oops, I was using the beta-5 tag; latest master branch works! Thanks again!!
