### ISSUE TITLE
Aiming doesn't work from a distance

### ISSUE THREAD

**Issue by stevenvachon** [AFADoomer/Wolf3D-TC-3.0#27]
If I aim directly at someone from a distance, it consistently misses until I move in closer. This pretty much prevents me from playing the game.

**Comment by AFADoomer** [comment]
What kind of distance are you talking about?

This is how the original game worked.  If you are more than 256 map units away (4 Wolf3D blocks), your maximum damage amount is reduced by about a third and you have a chance to miss completely.

**Comment by stevenvachon** [comment]
It misses completely every time. I can play the original and kill everything

**Comment by stevenvachon** [comment]
The distance of the soldier at the end of the first wooden hallway in the first level of the first episode of the original game.

**Comment by AFADoomer** [comment]
I just killed him with one shot with the pistol while standing in the southern doorway into that room.  I played again and it took three shots to kill him.

I did the same in the original game and had much the same experience.

The code for calculating damage amount is literally the same logic:
Original Wolf3D:
```
	if (dist<2)
		damage = US_RndT() / 4;
	else if (dist<4)
		damage = US_RndT() / 6;
	else
	{
		if ( (US_RndT() / 12) < dist)		// missed
			return;
		damage = US_RndT() / 6;
	}
```

This mod:
```
			dmg = GameHandler.WolfRandom();

			...

			if (dist < 2) { dmg /= 4; }
			else if (dist < 4) { dmg /= 6; }
			else
			{
				if ((GameHandler.WolfRandom() / 12) < dist) { dmg = 0; }
				else { dmg /= 6; }
			}
```

You may just be getting "unlucky" random rolls that make you miss...  At that distance (10-12 blocks), you have about a 50% chance of missing.

**Comment by stevenvachon** [comment]
![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/170197/229367026-e9f6ae4c-a787-475c-afbb-b4c576de4029.gif)

**Comment by stevenvachon** [comment]
Is the behavior of the random function the same as the original?

**Comment by stevenvachon** [comment]
This is no longer occurring on my end.
