### ISSUE TITLE
Frozen enemies

### ISSUE THREAD

**Issue by jackrjli** [AFADoomer/Wolf3D-TC-3.0#41]
When playing this, I occasionally encounter enemies that are frozen in place, responding to neither sight nor sound, until they are attacked. I have two save files (for GZDoom 4.12.2) showing this on E3L1 and E6L1:
[e3l1.zip](https://github.com/user-attachments/files/15722221/e3l1.zip)
[e6l1.zip](https://github.com/user-attachments/files/15722222/e6l1.zip)

I've encountered these frozen enemies at various points in my playthrough, but the attached E3L1 save is the only time I thought to save after encountering it. I've tried reloading an earlier save when this happens, and the problem doesn't occur again when I reach the same place.

E6L1 is the only place I've been able to reliably reproduce this phenomenon (the attached save is from one of those times):

1. Launch E6L1 on "Bring 'em on!" difficulty.
2. Go through the first door on the right, then in that hallway open the first door on the right (which leads to a small room with two SS, the one where the attached save file is set).
3. Kill one of the SS while standing in the corridor, outside their vision (if you stand at the edge of the corridor after opening the door, you should be able to just barely see the SS on the opposite side, without them seeing you).
4. After one SS is dead, you can enter the room and the other SS won't respond.

FWIW, I tried this level in DOSBox and found that both SS wake up immediately if I fire from the corridor.

**Comment by jackrjli** [comment]
The problem seems to be that when you shoot an enemy without them seeing you, their target is null, so the part in ActivatePeers() that says
```
mo.target = target;
mo.SetState(SeeState);
```
causes the other enemies to freeze. Not sure how to fix that, though.

**Comment by AFADoomer** [comment]
Thanks for the report!  I think I've fixed this as of b118b5b540cece3a4dbad5a0c7159eb8adba1148.  Can you confirm, please?

**Comment by jackrjli** [comment]
@AFADoomer Yes, it looks like that works. Thanks for the fix and for the great TC!
