### ISSUE TITLE
Feature Request : Option to add hints to pushwalls.

### ISSUE THREAD

**Issue by De-Seppe** [AFADoomer/Wolf3D-TC-3.0#42]
Could it be possible to add a toggleable option that adjusts the colormap value of pushwalls to make them recognizable?
It would also be possible have multiple settings (bigger offset in colormap) to make it easier or more difficult to see the effect.
This is similar to how pushwalls and pushplates are detectable in Rise of the Triad (on lower difficulties).
This would make it possible to play the game without constant wallhumping.

**Comment by AFADoomer** [comment]
Added the 'g_highlightpushwalls' console variable in 4e19e0d5542ad54abeb75292f91b31abd1b07e15 that adds gold/yellow shading to un-pushed pushwalls.

It's not in the menus, but I may add it later.
