### ISSUE TITLE
Script Error on latest Dev Build of GZDoom

### ISSUE THREAD

**Issue by Trimint123** [AFADoomer/Wolf3D-TC-3.0#44]
In case you wonder what version was causes it: g4.13pre-130-ged3941353 (2024-09-12)
![image](https://github.com/user-attachments/assets/d102b8a9-ab0c-4d50-81e4-9ec5e6e5d802)

**Comment by AFADoomer** [comment]
Thanks!  Should be fixed after a09ccfa4cc1e4181cab24068c5e3e7b8c58d9ed8.

Back-ported some functionality from Chalice of Glory and missed renaming the CVar in one spot.
