### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by stevenvachon** [AFADoomer/Wolf3D-TC-3.0#46]
> Script error, "Wolf3D-TC-3.0.ipk3:scripts/menus/slideshowmenu.zs" line 2695:
Too many arguments in call to Init

Why are broken changes being pushed?

**Comment by AFADoomer** [comment]
This works fine for me with GZDoom 4.13 (the current engine release) and the 4.14 dev builds...

**Comment by stevenvachon** [comment]
Thank you! Updating from 4.11.3 to 4.13 works.
