### ISSUE TITLE
Don't reset lives when you die?

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#6]
I know lives are useless in Wolf3D (because you can quick-save...), but I noticed lives get reset to 3 when you die instead of keeping the correct number 🙃
Is it possible to change this for purists?

**Comment by AFADoomer** [comment]
This should be fixed as of current version...  There may be conflicts if autosave kicks in that mean you are actually loading the last game instead of actually reloading after death.  I'll set the default value of the disableautosave CVar in future builds.

**Comment by Hexaae** [comment]
Mmmh, tried last version but I get this error with GZDoom:
![image](https://user-images.githubusercontent.com/8591462/199757819-c70898b2-591f-43e0-b015-ee2e0a07ceab.png)

I use the zip archive (renamed as .ipk3)

**Comment by Hexaae** [comment]
Updated to GZDoom 4.8.2 (current latest):

![image](https://user-images.githubusercontent.com/8591462/199759718-30814346-4b39-420e-801b-f9953554d505.png)

**Comment by Hexaae** [comment]
Another try:

_Script error, "Wolf3D-TC-3.0-master.ipk3:animdefs.txt" line 15:
Bad syntax._

**Comment by AFADoomer** [comment]
It's not fixed completely...  If autosaves are disabled, lives always reset to 3.  Should be OK with autosaves turned on (engine default).

You have to use a GZDoom dev build to run this current codebase - I'm going to hold off on a full release until the next GZDoom release.

**Comment by AFADoomer** [comment]
This should be fixed now.  Can you confirm?

**Comment by Hexaae** [comment]
See https://github.com/AFADoomer/Wolf3D-TC-3.0/issues/8#issuecomment-1310005956
