### ISSUE TITLE
Red screen when you die: if you press ESC you can't see menu

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#8]
After you die the screen becomes totally red. At this point if you press ESC you can hear sound but can't see menu...
Would be also useful a notification to press USE/OPEN key to continue.

**Comment by Hexaae** [comment]
Seems to happen randomly when you press ESC after red death screen. 
How to reproduce: after you die, switch between game and menu pressing ESC and 'Back to the Game' (use Return key) a dozen of times...

**Comment by AFADoomer** [comment]
This should be fixed as of a38d2ee261ef0c1139a117ec32c980a95dbb64cd

**Comment by Hexaae** [comment]
Not exactly. It works fine if you just die and then press "Use key" (E) to continue after the red screen... But strange things happen if you press ESC after red screen, and choose a New Game: it won't reset life counter to 3.

May also ask you a pair of other fixes/improvements?
- after you die (red screen) let player continue also with LMB, not just "Use key" (E). Much more intuitive.
- if you die (res screen), press ESC, and then select Return to Game (to the red screen!), the game will use in-game ready music as if you restarted the game, even if you're still at the red screen. Confusing. Music shouldn't change 'till you actually (re)start the game.

**Comment by AFADoomer** [comment]
Can you try after commit 26b99782114253e3f18c71524452501d197553ad?

I added the automatic respawn and fade in from red, as in the original game...  You can probably still trigger the bug if you spam ESC right after dying, but it's less likely now.

**Comment by Hexaae** [comment]
Much better and very close to the original DOS! 👍🏻
This workarounds many of the above issues... Yep, spamming ESC when dying I'm still able to start a New Game with wrong lives counter. Disabling ESC while dying could be a cheap fix now ;-)

P.S.
LMB to click/start on the Episode selection screen?

**Comment by AFADoomer** [comment]
Fixed the episode selection screen in 86f4bb8e5a1024eb60b802187bf9bd710903ef8b.

**Comment by AFADoomer** [comment]
I think I've fixed the ESC issue now as of 33fa7121917f05b6507f18af4d06c5fcce658aee.

**Comment by Hexaae** [comment]
With [4147bc8](https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/4147bc87e79535988a22a4abb8025fb1213fc5ca) I'm still able to interrupt the dying red-screen sequence and start a New Game, with wrong lives counter...

**Comment by AFADoomer** [comment]
OK, please try after 3d51137a9c9d5a5e5b293a2ab04f7783b3d41710.  I added a call in the menu code to force resetting some variables if you start a new game.

**Comment by Hexaae** [comment]
Works great now! Thank you! :-) 👍

**Comment by Hexaae** [comment]
Just found a bug (?): completed E1L1 and opened the secret wall to the secret "purple level"... Lives: 1, got reset and became 3.

P.S.
DIFFICULTY BUG?
It's just my impression or the game seems easier than the DOS original: less fire damage, and nazis firing less than expected at the most difficult level ("I am death incarnate")? Playing this online version https://www.silvergames.com/en/wolfenstein-3d it seems so...

**Comment by Hexaae** [comment]
Death sequence:
I've noticed there is a small difference with the original game: while turning the cam to your killer on the death sequence the screen should be covered by a ~10% red layer already.
