### ISSUE TITLE
Bad syntax error with last 3 updates

### ISSUE THREAD

**Issue by weishen1121** [AFADoomer/Wolf3D-TC-3.0#9]
Hi, here is the error I am getting:

```
Script error, "Wolf3D-TC-3.0-master.pk3:animdefs.txt" line 15:
Bad syntax.
```

The last build that works for me is from 9/7 titled 'Added SoD Finale Sequence' but all 3 newer ones keep giving me the Syntax error.

**Comment by AFADoomer** [comment]
You'll need to use one of the newer v4.9 development builds of GZDoom (something newer than ~25 July).

**Comment by weishen1121** [comment]
That worked ty!
